apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kp-brokers
  namespace: streaming
  labels:
    strimzi.io/cluster: doa-kafka
spec:
  replicas: 1
  roles: [ broker ]
  storage:
    type: persistent-claim
    size: 20Gi
    class: standard          # (선택) 사용할 StorageClass 명시
    deleteClaim: false       # Kafka 삭제해도 PVC는 남도록 (기본은 false 권장)
