apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: doa-connect
  namespace: streaming
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.9.1
  replicas: 1
  bootstrapServers: doa-kafka-kafka-bootstrap:9092

  # ➡ 반드시 Strimzi 베이스 이미지여야 합니다
  #image: quay.io/strimzi/kafka:0.47.0-kafka-3.9.1

  resources:
    requests: { cpu: "500m", memory: "1Gi" }
    limits:   { cpu: "2",    memory: "4Gi" }

  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"

    # Secret ConfigProvider (커넥터에서 ${secrets:...} 사용)
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider

  # ➡ Debezium 플러그인을 이미지에 Bake
  build:
    output:
      type: docker
      image: index.docker.io/ganplank/doa-connect:pg-2.6   # ⬅ 본인 레포/태그
      pushSecret: regcred                                  # ⬅ 방금 만든 시크릿
    plugins:
      - name: debezium-postgres
        artifacts:
          - type: maven
            repository: https://repo1.maven.org/maven2
            group: io.debezium
            artifact: debezium-connector-postgres
            version: 2.6.0.Final

