apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: doa-kafka
  namespace: streaming
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 3.9.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1           #consumer group의 offset 내부 토픽 __consumer_offests 의 복제 개수
      transaction.state.log.replication.factor: 1   #Transaction coordinator 사용하는 내부 토픽, __transaction_state
      transaction.state.log.min.isr: 1              #__transaction_state 토픽의 파티션에서 정상적인 트랜잭션 커밋을 위해 동기화 상태를 유지해야 하는 최소 복제본 수 (ISR, In-Sync Replicas)
      default.replication.factor: 1                 #새로운 토픽이 생성될 때 적용되는 default 복제 개수
      min.insync.replicas: 1                        #acks=all 설정했을 때 쓰기 요청을 성공으로 간주하기 위해 동기화된 상태를 유지해야 하는 최소 복제본 수 
  entityOperator:
    topicOperator: {}
    userOperator: {}

